// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LAPTOP-MOD8PJ2Q
// DateTime: 21.06.2020 14:02:36
// UserName: przem
// Input file <Parser.y - 21.06.2020 14:02:26>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace GardensPoint
{
public enum Tokens {error=2,EOF=3,Comment=4,DoubleConv=5,IntConv=6,
    Write=7,Program=8,If=9,Else=10,While=11,Read=12,
    Int=13,Double=14,Bool=15,True=16,False=17,Return=18,
    And=19,BitAnd=20,Or=21,BitOr=22,Negation=23,BitNegation=24,
    Equal=25,NotEqual=26,GreaterOrEqual=27,SmallerOrEqual=28,Smaller=29,Greater=30,
    Assign=31,Plus=32,Minus=33,Multiply=34,Divide=35,OpenPar=36,
    ClosePar=37,OpenBracket=38,CloseBracket=39,Endl=40,Eof=41,Error=42,
    Ident=43,IntNumber=44,RealNumber=45,String=46,SemiCol=47};

public struct ValueType
#line 4 "Parser.y"
{
public string  val;
public int i_val;
public double  d_val;
public string  type;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[98];
  private static State[] states = new State[173];
  private static string[] nonTerms = new string[] {
      "identPar", "maincandeclare", "main", "declare", "vtype", "assign", "exp", 
      "exp2", "exp3", "exp4", "exp5", "exp6", "logicop", "addop", "unary", "relatiop", 
      "mulop", "bitop", "term", "read", "while", "whilebody", "if", "start", 
      "$accept", "ifbody", "semicol", "expression", "write", "Anon@1", "Anon@2", 
      "Anon@3", };

  static Parser() {
    states[0] = new State(new int[]{8,3},new int[]{-24,1});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{38,4});
    states[4] = new State(new int[]{13,14,14,15,15,16,12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-2,5,-4,8,-5,10,-3,17,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[5] = new State(new int[]{39,6});
    states[6] = new State(new int[]{41,7});
    states[7] = new State(-2);
    states[8] = new State(new int[]{13,14,14,15,15,16,12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-2,9,-4,8,-5,10,-3,17,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[9] = new State(-17);
    states[10] = new State(new int[]{43,11});
    states[11] = new State(new int[]{47,13},new int[]{-27,12});
    states[12] = new State(-41);
    states[13] = new State(-5);
    states[14] = new State(-42);
    states[15] = new State(-43);
    states[16] = new State(-44);
    states[17] = new State(-18);
    states[18] = new State(new int[]{12,24,7,31,47,13},new int[]{-28,19,-27,171,-20,23,-29,30});
    states[19] = new State(-21,new int[]{-30,20});
    states[20] = new State(new int[]{47,13},new int[]{-27,21});
    states[21] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,22,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[22] = new State(-22);
    states[23] = new State(-19);
    states[24] = new State(new int[]{43,26,36,27},new int[]{-1,25});
    states[25] = new State(-14);
    states[26] = new State(-12);
    states[27] = new State(new int[]{43,26,36,27},new int[]{-1,28});
    states[28] = new State(new int[]{37,29});
    states[29] = new State(-13);
    states[30] = new State(-20);
    states[31] = new State(new int[]{46,33,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,32,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[32] = new State(-15);
    states[33] = new State(-16);
    states[34] = new State(new int[]{21,117,19,118,47,-49,12,-49,7,-49,37,-49},new int[]{-13,35});
    states[35] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,36,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[36] = new State(-46);
    states[37] = new State(new int[]{25,109,26,110,30,111,29,112,27,113,28,114,21,-55,19,-55,47,-55,12,-55,7,-55,37,-55},new int[]{-16,38});
    states[38] = new State(new int[]{36,40,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-8,39,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84});
    states[39] = new State(-51);
    states[40] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,41,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[41] = new State(new int[]{37,42});
    states[42] = new State(new int[]{22,48,20,49,34,60,35,61,32,100,33,101,25,109,26,110,30,111,29,112,27,113,28,114,21,-54,19,-54,47,-54,12,-54,7,-54,37,-54},new int[]{-18,43,-17,56,-14,95,-16,104});
    states[43] = new State(new int[]{36,45,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-11,44,-12,68,-15,74,-19,84});
    states[44] = new State(-67);
    states[45] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,46,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[46] = new State(new int[]{37,47});
    states[47] = new State(new int[]{22,48,20,49,34,-69,35,-69,32,-69,33,-69,25,-69,26,-69,30,-69,29,-69,27,-69,28,-69,21,-69,19,-69,47,-69,12,-69,7,-69,37,-69},new int[]{-18,43});
    states[48] = new State(-83);
    states[49] = new State(-84);
    states[50] = new State(new int[]{32,100,33,101,25,-60,26,-60,30,-60,29,-60,27,-60,28,-60,21,-60,19,-60,47,-60,12,-60,7,-60,37,-60},new int[]{-14,51});
    states[51] = new State(new int[]{36,53,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-9,52,-10,50,-11,62,-12,68,-15,74,-19,84});
    states[52] = new State(-56);
    states[53] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,54,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[54] = new State(new int[]{37,55});
    states[55] = new State(new int[]{22,48,20,49,34,60,35,61,32,100,33,101,25,-58,26,-58,30,-58,29,-58,27,-58,28,-58,21,-58,19,-58,47,-58,12,-58,7,-58,37,-58},new int[]{-18,43,-17,56,-14,95});
    states[56] = new State(new int[]{36,57,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-10,119,-11,62,-12,68,-15,74,-19,84});
    states[57] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,58,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[58] = new State(new int[]{37,59});
    states[59] = new State(new int[]{22,48,20,49,34,60,35,61,32,-62,33,-62,25,-62,26,-62,30,-62,29,-62,27,-62,28,-62,21,-62,19,-62,47,-62,12,-62,7,-62,37,-62},new int[]{-18,43,-17,56});
    states[60] = new State(-81);
    states[61] = new State(-82);
    states[62] = new State(new int[]{34,60,35,61,32,-65,33,-65,25,-65,26,-65,30,-65,29,-65,27,-65,28,-65,21,-65,19,-65,47,-65,12,-65,7,-65,37,-65},new int[]{-17,63});
    states[63] = new State(new int[]{36,65,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-10,64,-11,62,-12,68,-15,74,-19,84});
    states[64] = new State(-61);
    states[65] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,66,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[66] = new State(new int[]{37,67});
    states[67] = new State(new int[]{22,48,20,49,34,60,35,61,32,-64,33,-64,25,-64,26,-64,30,-64,29,-64,27,-64,28,-64,21,-64,19,-64,47,-64,12,-64,7,-64,37,-64},new int[]{-18,43,-17,56});
    states[68] = new State(new int[]{22,48,20,49,34,-70,35,-70,32,-70,33,-70,25,-70,26,-70,30,-70,29,-70,27,-70,28,-70,21,-70,19,-70,47,-70,12,-70,7,-70,37,-70},new int[]{-18,69});
    states[69] = new State(new int[]{36,71,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-11,70,-12,68,-15,74,-19,84});
    states[70] = new State(-66);
    states[71] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,72,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[72] = new State(new int[]{37,73});
    states[73] = new State(new int[]{22,48,20,49,34,-68,35,-68,32,-68,33,-68,25,-68,26,-68,30,-68,29,-68,27,-68,28,-68,21,-68,19,-68,47,-68,12,-68,7,-68,37,-68},new int[]{-18,43});
    states[74] = new State(new int[]{36,76,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-12,75,-15,74,-19,84});
    states[75] = new State(-71);
    states[76] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,77,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[77] = new State(new int[]{37,78});
    states[78] = new State(-72);
    states[79] = new State(-85);
    states[80] = new State(-86);
    states[81] = new State(-87);
    states[82] = new State(-88);
    states[83] = new State(-89);
    states[84] = new State(-73);
    states[85] = new State(new int[]{31,86,22,-74,20,-74,34,-74,35,-74,32,-74,33,-74,25,-74,26,-74,30,-74,29,-74,27,-74,28,-74,21,-74,19,-74,47,-74,12,-74,7,-74,37,-74});
    states[86] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,87,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[87] = new State(-45);
    states[88] = new State(-75);
    states[89] = new State(-76);
    states[90] = new State(-77);
    states[91] = new State(-78);
    states[92] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,93,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[93] = new State(new int[]{37,94});
    states[94] = new State(new int[]{22,48,20,49,34,60,35,61,32,100,33,101,25,109,26,110,30,111,29,112,27,113,28,114,21,117,19,118,47,-48,12,-48,7,-48,37,-48},new int[]{-18,43,-17,56,-14,95,-16,104,-13,115});
    states[95] = new State(new int[]{36,97,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-9,96,-10,50,-11,62,-12,68,-15,74,-19,84});
    states[96] = new State(-57);
    states[97] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,98,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[98] = new State(new int[]{37,99});
    states[99] = new State(new int[]{22,48,20,49,34,60,35,61,32,100,33,101,25,-59,26,-59,30,-59,29,-59,27,-59,28,-59,21,-59,19,-59,47,-59,12,-59,7,-59,37,-59},new int[]{-18,43,-17,56,-14,95});
    states[100] = new State(-79);
    states[101] = new State(-80);
    states[102] = new State(-50);
    states[103] = new State(-74);
    states[104] = new State(new int[]{36,106,33,79,24,80,23,81,6,82,5,83,43,103,45,88,44,89,16,90,17,91},new int[]{-8,105,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84});
    states[105] = new State(-52);
    states[106] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,107,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[107] = new State(new int[]{37,108});
    states[108] = new State(new int[]{22,48,20,49,34,60,35,61,32,100,33,101,25,109,26,110,30,111,29,112,27,113,28,114,21,-53,19,-53,47,-53,12,-53,7,-53,37,-53},new int[]{-18,43,-17,56,-14,95,-16,104});
    states[109] = new State(-92);
    states[110] = new State(-93);
    states[111] = new State(-94);
    states[112] = new State(-95);
    states[113] = new State(-96);
    states[114] = new State(-97);
    states[115] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,116,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[116] = new State(-47);
    states[117] = new State(-90);
    states[118] = new State(-91);
    states[119] = new State(-63);
    states[120] = new State(new int[]{47,13},new int[]{-27,121});
    states[121] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,122,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[122] = new State(-24);
    states[123] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,124,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[124] = new State(-25);
    states[125] = new State(new int[]{36,126});
    states[126] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,127,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[127] = new State(new int[]{37,128});
    states[128] = new State(new int[]{38,129,12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,18,169},new int[]{-22,162,-28,163,-20,23,-29,30,-7,165,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,167,-23,168});
    states[129] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,130,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[130] = new State(new int[]{39,131});
    states[131] = new State(-34);
    states[132] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,133,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[133] = new State(-26);
    states[134] = new State(new int[]{36,135});
    states[135] = new State(new int[]{33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92},new int[]{-7,136,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102});
    states[136] = new State(new int[]{37,137});
    states[137] = new State(new int[]{38,141,12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,18,160},new int[]{-26,138,-28,154,-20,23,-29,30,-7,156,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,158,-23,159});
    states[138] = new State(new int[]{10,139,12,-3,7,-3,33,-3,24,-3,23,-3,6,-3,5,-3,43,-3,45,-3,44,-3,16,-3,17,-3,36,-3,11,-3,9,-3,2,-3,18,-3,39,-3});
    states[139] = new State(new int[]{38,141,12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,18,160},new int[]{-26,140,-28,154,-20,23,-29,30,-7,156,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,158,-23,159});
    states[140] = new State(-4);
    states[141] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,142,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[142] = new State(new int[]{39,143});
    states[143] = new State(-6);
    states[144] = new State(new int[]{41,153,47,13,12,-29,7,-29,33,-29,24,-29,23,-29,6,-29,5,-29,43,-29,45,-29,44,-29,16,-29,17,-29,36,-29,11,-29,9,-29,2,-29,18,-29,39,-29},new int[]{-27,145,-32,151});
    states[145] = new State(-27,new int[]{-31,146});
    states[146] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,147,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[147] = new State(-28);
    states[148] = new State(new int[]{47,13},new int[]{-27,149});
    states[149] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,150,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[150] = new State(-32);
    states[151] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,152,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[152] = new State(-30);
    states[153] = new State(-31);
    states[154] = new State(new int[]{47,13},new int[]{-27,155});
    states[155] = new State(-7);
    states[156] = new State(new int[]{47,13},new int[]{-27,157});
    states[157] = new State(-8);
    states[158] = new State(-9);
    states[159] = new State(-10);
    states[160] = new State(new int[]{47,13},new int[]{-27,161});
    states[161] = new State(-11);
    states[162] = new State(-35);
    states[163] = new State(new int[]{47,13},new int[]{-27,164});
    states[164] = new State(-36);
    states[165] = new State(new int[]{47,13},new int[]{-27,166});
    states[166] = new State(-37);
    states[167] = new State(-38);
    states[168] = new State(-39);
    states[169] = new State(new int[]{47,13},new int[]{-27,170});
    states[170] = new State(-40);
    states[171] = new State(new int[]{12,24,7,31,33,79,24,80,23,81,6,82,5,83,43,85,45,88,44,89,16,90,17,91,36,92,11,125,9,134,2,144,18,148,39,-33},new int[]{-3,172,-28,18,-20,23,-29,30,-7,120,-8,34,-9,37,-10,50,-11,62,-12,68,-15,74,-19,84,-6,102,-21,123,-23,132});
    states[172] = new State(-23);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-25, new int[]{-24,3});
    rules[2] = new Rule(-24, new int[]{8,38,-2,39,41});
    rules[3] = new Rule(-23, new int[]{9,36,-7,37,-26});
    rules[4] = new Rule(-23, new int[]{9,36,-7,37,-26,10,-26});
    rules[5] = new Rule(-27, new int[]{47});
    rules[6] = new Rule(-26, new int[]{38,-3,39});
    rules[7] = new Rule(-26, new int[]{-28,-27});
    rules[8] = new Rule(-26, new int[]{-7,-27});
    rules[9] = new Rule(-26, new int[]{-21});
    rules[10] = new Rule(-26, new int[]{-23});
    rules[11] = new Rule(-26, new int[]{18,-27});
    rules[12] = new Rule(-1, new int[]{43});
    rules[13] = new Rule(-1, new int[]{36,-1,37});
    rules[14] = new Rule(-20, new int[]{12,-1});
    rules[15] = new Rule(-29, new int[]{7,-7});
    rules[16] = new Rule(-29, new int[]{7,46});
    rules[17] = new Rule(-2, new int[]{-4,-2});
    rules[18] = new Rule(-2, new int[]{-3});
    rules[19] = new Rule(-28, new int[]{-20});
    rules[20] = new Rule(-28, new int[]{-29});
    rules[21] = new Rule(-30, new int[]{});
    rules[22] = new Rule(-3, new int[]{-28,-28,-30,-27,-3});
    rules[23] = new Rule(-3, new int[]{-28,-27,-3});
    rules[24] = new Rule(-3, new int[]{-7,-27,-3});
    rules[25] = new Rule(-3, new int[]{-21,-3});
    rules[26] = new Rule(-3, new int[]{-23,-3});
    rules[27] = new Rule(-31, new int[]{});
    rules[28] = new Rule(-3, new int[]{2,-27,-31,-3});
    rules[29] = new Rule(-32, new int[]{});
    rules[30] = new Rule(-3, new int[]{2,-32,-3});
    rules[31] = new Rule(-3, new int[]{2,41});
    rules[32] = new Rule(-3, new int[]{18,-27,-3});
    rules[33] = new Rule(-3, new int[]{});
    rules[34] = new Rule(-21, new int[]{11,36,-7,37,38,-3,39});
    rules[35] = new Rule(-21, new int[]{11,36,-7,37,-22});
    rules[36] = new Rule(-22, new int[]{-28,-27});
    rules[37] = new Rule(-22, new int[]{-7,-27});
    rules[38] = new Rule(-22, new int[]{-21});
    rules[39] = new Rule(-22, new int[]{-23});
    rules[40] = new Rule(-22, new int[]{18,-27});
    rules[41] = new Rule(-4, new int[]{-5,43,-27});
    rules[42] = new Rule(-5, new int[]{13});
    rules[43] = new Rule(-5, new int[]{14});
    rules[44] = new Rule(-5, new int[]{15});
    rules[45] = new Rule(-6, new int[]{43,31,-7});
    rules[46] = new Rule(-7, new int[]{-8,-13,-7});
    rules[47] = new Rule(-7, new int[]{36,-7,37,-13,-7});
    rules[48] = new Rule(-7, new int[]{36,-7,37});
    rules[49] = new Rule(-7, new int[]{-8});
    rules[50] = new Rule(-7, new int[]{-6});
    rules[51] = new Rule(-8, new int[]{-9,-16,-8});
    rules[52] = new Rule(-8, new int[]{36,-7,37,-16,-8});
    rules[53] = new Rule(-8, new int[]{36,-7,37,-16,36,-7,37});
    rules[54] = new Rule(-8, new int[]{-9,-16,36,-7,37});
    rules[55] = new Rule(-8, new int[]{-9});
    rules[56] = new Rule(-9, new int[]{-10,-14,-9});
    rules[57] = new Rule(-9, new int[]{36,-7,37,-14,-9});
    rules[58] = new Rule(-9, new int[]{-10,-14,36,-7,37});
    rules[59] = new Rule(-9, new int[]{36,-7,37,-14,36,-7,37});
    rules[60] = new Rule(-9, new int[]{-10});
    rules[61] = new Rule(-10, new int[]{-11,-17,-10});
    rules[62] = new Rule(-10, new int[]{36,-7,37,-17,36,-7,37});
    rules[63] = new Rule(-10, new int[]{36,-7,37,-17,-10});
    rules[64] = new Rule(-10, new int[]{-11,-17,36,-7,37});
    rules[65] = new Rule(-10, new int[]{-11});
    rules[66] = new Rule(-11, new int[]{-12,-18,-11});
    rules[67] = new Rule(-11, new int[]{36,-7,37,-18,-11});
    rules[68] = new Rule(-11, new int[]{-12,-18,36,-7,37});
    rules[69] = new Rule(-11, new int[]{36,-7,37,-18,36,-7,37});
    rules[70] = new Rule(-11, new int[]{-12});
    rules[71] = new Rule(-12, new int[]{-15,-12});
    rules[72] = new Rule(-12, new int[]{-15,36,-7,37});
    rules[73] = new Rule(-12, new int[]{-19});
    rules[74] = new Rule(-19, new int[]{43});
    rules[75] = new Rule(-19, new int[]{45});
    rules[76] = new Rule(-19, new int[]{44});
    rules[77] = new Rule(-19, new int[]{16});
    rules[78] = new Rule(-19, new int[]{17});
    rules[79] = new Rule(-14, new int[]{32});
    rules[80] = new Rule(-14, new int[]{33});
    rules[81] = new Rule(-17, new int[]{34});
    rules[82] = new Rule(-17, new int[]{35});
    rules[83] = new Rule(-18, new int[]{22});
    rules[84] = new Rule(-18, new int[]{20});
    rules[85] = new Rule(-15, new int[]{33});
    rules[86] = new Rule(-15, new int[]{24});
    rules[87] = new Rule(-15, new int[]{23});
    rules[88] = new Rule(-15, new int[]{6});
    rules[89] = new Rule(-15, new int[]{5});
    rules[90] = new Rule(-13, new int[]{21});
    rules[91] = new Rule(-13, new int[]{19});
    rules[92] = new Rule(-16, new int[]{25});
    rules[93] = new Rule(-16, new int[]{26});
    rules[94] = new Rule(-16, new int[]{30});
    rules[95] = new Rule(-16, new int[]{29});
    rules[96] = new Rule(-16, new int[]{27});
    rules[97] = new Rule(-16, new int[]{28});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> Program, OpenBracket, maincandeclare, CloseBracket, Eof
#line 18 "Parser.y"
                                                            { Compiler.tree = Compiler.stackTree.Pop();}
#line default
        break;
      case 3: // if -> If, OpenPar, exp, ClosePar, ifbody
#line 21 "Parser.y"
                                    { var nodeI = new IfNode();
					nodeI.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeI.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeI.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeI);}
#line default
        break;
      case 4: // if -> If, OpenPar, exp, ClosePar, ifbody, Else, ifbody
#line 26 "Parser.y"
                                               { var nodeI =new IfElseNode();
					nodeI.line=Compiler.line; 
					if(Compiler.stackTree.Count>0) nodeI.elseNode = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) nodeI.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeI.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeI);}
#line default
        break;
      case 5: // semicol -> SemiCol
#line 33 "Parser.y"
                 {
					Compiler.line=ValueStack[ValueStack.Depth-1].i_val;}
#line default
        break;
      case 11: // ifbody -> Return, semicol
#line 41 "Parser.y"
                  { var nodeM = new ReturnNode();
		nodeM.line=Compiler.line; 
		 Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 12: // identPar -> Ident
#line 45 "Parser.y"
                {CurrentSemanticValue.type=ValueStack[ValueStack.Depth-1].val;}
#line default
        break;
      case 13: // identPar -> OpenPar, identPar, ClosePar
#line 46 "Parser.y"
                             {CurrentSemanticValue.type =ValueStack[ValueStack.Depth-2].type;}
#line default
        break;
      case 14: // read -> Read, identPar
#line 47 "Parser.y"
                    { var node = new IdentNode();
					node.ident = ValueStack[ValueStack.Depth-1].type;
					node.line=Compiler.line;
					Compiler.stackTree.Push(node); 
					var nodeR = new ReadNode();
					if(Compiler.stackTree.Count>0) nodeR.right = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeR);}
#line default
        break;
      case 15: // write -> Write, exp
#line 54 "Parser.y"
                { var nodeW = new WriteNode();
					nodeW.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeW.right = Compiler.stackTree.Pop();
					    Compiler.stackTree.Push(nodeW);}
#line default
        break;
      case 16: // write -> Write, String
#line 59 "Parser.y"
                {
					var nodeS = new StringNode();
					nodeS.line=Compiler.line;
					nodeS.value = ValueStack[ValueStack.Depth-1].val;
					var nodeW = new WriteNode();
					nodeW.right=nodeS;
				    Compiler.stackTree.Push(nodeW);}
#line default
        break;
      case 17: // maincandeclare -> declare, maincandeclare
#line 68 "Parser.y"
     {  
				    var nodeM = new MainNode();
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 18: // maincandeclare -> main
#line 75 "Parser.y"
        {}
#line default
        break;
      case 21: // Anon@1 -> /* empty */
#line 81 "Parser.y"
                            {Console.WriteLine("Syntax error");  ++Compiler.errors;
               yyerrok();
                }
#line default
        break;
      case 23: // main -> expression, semicol, main
#line 85 "Parser.y"
    {  
				    var nodeM = new MainNode();
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 24: // main -> exp, semicol, main
#line 92 "Parser.y"
                    {  
				    var nodeM = new MainNode();
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 25: // main -> while, main
#line 99 "Parser.y"
              {  
				    var nodeM = new MainNode();
					nodeM.line=Compiler.line; 
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 26: // main -> if, main
#line 106 "Parser.y"
            {  
				    var nodeM = new MainNode();
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 27: // Anon@2 -> /* empty */
#line 113 "Parser.y"
                  {Console.WriteLine("Error while parsing (syntax or lexical error): in line {0} ", ValueStack[ValueStack.Depth-2].i_val);   ++Compiler.errors;
      yyerrok();
	              }
#line default
        break;
      case 29: // Anon@3 -> /* empty */
#line 116 "Parser.y"
         {Console.WriteLine("Error while parsing (syntax or lexical error)");   ++Compiler.errors;
        yyerrok();
              }
#line default
        break;
      case 31: // main -> error, Eof
#line 119 "Parser.y"
             {Console.WriteLine("Unexpected end of file");  ++Compiler.errors; YYAbort();}
#line default
        break;
      case 32: // main -> Return, semicol, main
#line 120 "Parser.y"
                       { var nodeR = new ReturnNode();
					nodeR.line=Compiler.line;
					Compiler.stackTree.Push(nodeR);
					var nodeM = new MainNode();
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 33: // main -> /* empty */
#line 128 "Parser.y"
    { var nodeM = new MainNode();
		 nodeM.line=Compiler.line;
		 Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 34: // while -> While, OpenPar, exp, ClosePar, OpenBracket, main, CloseBracket
#line 134 "Parser.y"
                                                                {var nodeW = new WhileNode();
					nodeW.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeW.right = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) nodeW.left = Compiler.stackTree.Pop();
					Compiler.stackTree.Push(nodeW);
					}
#line default
        break;
      case 35: // while -> While, OpenPar, exp, ClosePar, whilebody
#line 140 "Parser.y"
                                         {var nodeW = new WhileNode();
					nodeW.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeW.right = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) nodeW.left = Compiler.stackTree.Pop();
					Compiler.stackTree.Push(nodeW);
					}
#line default
        break;
      case 40: // whilebody -> Return, semicol
#line 151 "Parser.y"
                  { var nodeM = new ReturnNode();
		 Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 41: // declare -> vtype, Ident, semicol
#line 154 "Parser.y"
                              {var node = new DeclarationNode(); 
						  node.line=Compiler.line;
						  node.varType=ValueStack[ValueStack.Depth-3].type; node.ident=ValueStack[ValueStack.Depth-2].val;
						  if(Compiler.variables.ContainsKey(ValueStack[ValueStack.Depth-2].val)) 
						  {	
							string s=ValueStack[ValueStack.Depth-2].val;
							Console.WriteLine("Semantic error. Variable {0} already declared.",s);
							++Compiler.errors;
						  }
						  else
							 Compiler.variables.Add(ValueStack[ValueStack.Depth-2].val,ValueStack[ValueStack.Depth-3].type);
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 42: // vtype -> Int
#line 167 "Parser.y"
           {CurrentSemanticValue.type="int";}
#line default
        break;
      case 43: // vtype -> Double
#line 168 "Parser.y"
          {CurrentSemanticValue.type="double";}
#line default
        break;
      case 44: // vtype -> Bool
#line 169 "Parser.y"
        {CurrentSemanticValue.type = "bool";}
#line default
        break;
      case 45: // assign -> Ident, Assign, exp
#line 171 "Parser.y"
                          {var node = new AssignNode(); 
						   node.line=Compiler.line;
						   node.ident=ValueStack[ValueStack.Depth-3].val;
						   	if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 46: // exp -> exp2, logicop, exp
#line 178 "Parser.y"
                       {var node = new LogicNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 47: // exp -> OpenPar, exp, ClosePar, logicop, exp
#line 184 "Parser.y"
                                      {var node = new LogicNode(); 
					node.line=Compiler.line;
					 if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 51: // exp2 -> exp3, relatiop, exp2
#line 195 "Parser.y"
  {
		 var node = new RelationNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 52: // exp2 -> OpenPar, exp, ClosePar, relatiop, exp2
#line 203 "Parser.y"
   {var node = new RelationNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 53: // exp2 -> OpenPar, exp, ClosePar, relatiop, OpenPar, exp, ClosePar
#line 210 "Parser.y"
   {var node = new RelationNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 54: // exp2 -> exp3, relatiop, OpenPar, exp, ClosePar
#line 217 "Parser.y"
   {var node = new RelationNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 56: // exp3 -> exp4, addop, exp3
#line 225 "Parser.y"
                      {var node = new AddNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 57: // exp3 -> OpenPar, exp, ClosePar, addop, exp3
#line 231 "Parser.y"
                                   {var node = new AddNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 58: // exp3 -> exp4, addop, OpenPar, exp, ClosePar
#line 237 "Parser.y"
                                   {var node = new AddNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 59: // exp3 -> OpenPar, exp, ClosePar, addop, OpenPar, exp, ClosePar
#line 244 "Parser.y"
     {var node = new AddNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 61: // exp4 -> exp5, mulop, exp4
#line 252 "Parser.y"
                       {var node = new MulNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 62: // exp4 -> OpenPar, exp, ClosePar, mulop, OpenPar, exp, ClosePar
#line 258 "Parser.y"
                                                    {var node = new MulNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 63: // exp4 -> OpenPar, exp, ClosePar, mulop, exp4
#line 264 "Parser.y"
                                    {var node = new MulNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 64: // exp4 -> exp5, mulop, OpenPar, exp, ClosePar
#line 270 "Parser.y"
                                    {var node = new MulNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 66: // exp5 -> exp6, bitop, exp5
#line 278 "Parser.y"
                       {var node = new BitNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
					node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 67: // exp5 -> OpenPar, exp, ClosePar, bitop, exp5
#line 284 "Parser.y"
                                     {var node = new BitNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
						node.type = ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 68: // exp5 -> exp6, bitop, OpenPar, exp, ClosePar
#line 290 "Parser.y"
                                      {var node = new BitNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
						node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 69: // exp5 -> OpenPar, exp, ClosePar, bitop, OpenPar, exp, ClosePar
#line 296 "Parser.y"
                                                      {var node = new BitNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
						node.type = ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 71: // exp6 -> unary, exp6
#line 304 "Parser.y"
                   {var node = new UnaryNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type=ValueStack[ValueStack.Depth-2].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 72: // exp6 -> unary, OpenPar, exp, ClosePar
#line 309 "Parser.y"
                              {var node = new UnaryNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type=ValueStack[ValueStack.Depth-4].type;
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 74: // term -> Ident
#line 316 "Parser.y"
            {var node = new IdentNode();
			node.line=Compiler.line;
			node.ident = ValueStack[ValueStack.Depth-1].val;
			Compiler.stackTree.Push(node);}
#line default
        break;
      case 75: // term -> RealNumber
#line 320 "Parser.y"
              {var node = new DoubleNode();	
					node.line=Compiler.line;
					node.value=Double.Parse(ValueStack[ValueStack.Depth-1].val,System.Globalization.CultureInfo.InvariantCulture);
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 76: // term -> IntNumber
#line 324 "Parser.y"
             {var node = new IntNode();
					node.line=Compiler.line;
					node.value=Int32.Parse(ValueStack[ValueStack.Depth-1].val);
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 77: // term -> True
#line 328 "Parser.y"
        {var node = new BoolNode();
					node.line=Compiler.line;
					node.value=true;
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 78: // term -> False
#line 332 "Parser.y"
         {var node = new BoolNode();
					node.line=Compiler.line;
					node.value=false;
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 79: // addop -> Plus
#line 337 "Parser.y"
             {CurrentSemanticValue.type="+";}
#line default
        break;
      case 80: // addop -> Minus
#line 338 "Parser.y"
          {CurrentSemanticValue.type="-";}
#line default
        break;
      case 81: // mulop -> Multiply
#line 340 "Parser.y"
                 {CurrentSemanticValue.type="*";}
#line default
        break;
      case 82: // mulop -> Divide
#line 342 "Parser.y"
          {CurrentSemanticValue.type="/";}
#line default
        break;
      case 83: // bitop -> BitOr
#line 343 "Parser.y"
             {CurrentSemanticValue.type="||";}
#line default
        break;
      case 84: // bitop -> BitAnd
#line 344 "Parser.y"
            {CurrentSemanticValue.type="&&";}
#line default
        break;
      case 85: // unary -> Minus
#line 346 "Parser.y"
              {CurrentSemanticValue.type="-";}
#line default
        break;
      case 86: // unary -> BitNegation
#line 347 "Parser.y"
                {CurrentSemanticValue.type="~";}
#line default
        break;
      case 87: // unary -> Negation
#line 348 "Parser.y"
             {CurrentSemanticValue.type="!";}
#line default
        break;
      case 88: // unary -> IntConv
#line 349 "Parser.y"
            {CurrentSemanticValue.type="(int)";}
#line default
        break;
      case 89: // unary -> DoubleConv
#line 350 "Parser.y"
               {CurrentSemanticValue.type="(double)";}
#line default
        break;
      case 92: // relatiop -> Equal
#line 355 "Parser.y"
                 {CurrentSemanticValue.type="==";}
#line default
        break;
      case 93: // relatiop -> NotEqual
#line 356 "Parser.y"
             {CurrentSemanticValue.type="!=";}
#line default
        break;
      case 94: // relatiop -> Greater
#line 357 "Parser.y"
           {CurrentSemanticValue.type=">";}
#line default
        break;
      case 95: // relatiop -> Smaller
#line 358 "Parser.y"
            {CurrentSemanticValue.type="<";}
#line default
        break;
      case 96: // relatiop -> GreaterOrEqual
#line 359 "Parser.y"
                  {CurrentSemanticValue.type=">=";}
#line default
        break;
      case 97: // relatiop -> SmallerOrEqual
#line 360 "Parser.y"
                   {CurrentSemanticValue.type="<=";}
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 364 "Parser.y"

public Parser(Scanner scanner) : base(scanner) { }
#line default
}
}
