// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  LAPTOP-MOD8PJ2Q
// DateTime: 28.06.2020 01:13:56
// UserName: przem
// Input file <C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y - 28.06.2020 01:13:54>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace GardensPoint
{
public enum Tokens {error=2,EOF=3,Comment=4,DoubleConv=5,IntConv=6,
    Write=7,Program=8,If=9,Else=10,While=11,Read=12,
    Int=13,Double=14,Bool=15,True=16,False=17,Return=18,
    And=19,BitAnd=20,Or=21,BitOr=22,Negation=23,BitNegation=24,
    Equal=25,NotEqual=26,GreaterOrEqual=27,SmallerOrEqual=28,Smaller=29,Greater=30,
    Assign=31,Plus=32,Minus=33,Multiply=34,Divide=35,OpenPar=36,
    ClosePar=37,OpenBracket=38,CloseBracket=39,Endl=40,Eof=41,Error=42,
    Ident=43,IntNumber=44,RealNumber=45,String=46,SemiCol=47};

public struct ValueType
#line 4 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
{
public string  val;
public int i_val;
public string  type;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[103];
  private static State[] states = new State[186];
  private static string[] nonTerms = new string[] {
      "identPar", "maincandeclare", "main", "declare", "vtype", "assign", "exp", 
      "exp2", "exp3", "exp4", "exp5", "exp6", "logicop", "addop", "unary", "relatiop", 
      "mulop", "bitop", "term", "read", "while", "whilebody", "if", "semicol", 
      "start", "$accept", "ifbody", "expression", "write", "Anon@1", "exp1", 
      "Anon@2", "Anon@3", "assignMid", };

  static Parser() {
    states[0] = new State(new int[]{8,3},new int[]{-25,1});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{38,4,41,185});
    states[4] = new State(new int[]{13,14,14,15,15,16,12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-2,5,-4,8,-5,10,-3,17,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[5] = new State(new int[]{39,6});
    states[6] = new State(new int[]{41,7});
    states[7] = new State(-2);
    states[8] = new State(new int[]{13,14,14,15,15,16,12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-2,9,-4,8,-5,10,-3,17,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[9] = new State(-18);
    states[10] = new State(new int[]{43,11});
    states[11] = new State(new int[]{47,13},new int[]{-24,12});
    states[12] = new State(-44);
    states[13] = new State(-6);
    states[14] = new State(-45);
    states[15] = new State(-46);
    states[16] = new State(-47);
    states[17] = new State(-19);
    states[18] = new State(new int[]{12,24,7,31,47,13},new int[]{-28,19,-24,183,-20,23,-29,30});
    states[19] = new State(-22,new int[]{-30,20});
    states[20] = new State(new int[]{47,13},new int[]{-24,21});
    states[21] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,22,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[22] = new State(-23);
    states[23] = new State(-20);
    states[24] = new State(new int[]{43,26,36,27},new int[]{-1,25});
    states[25] = new State(-15);
    states[26] = new State(-13);
    states[27] = new State(new int[]{43,26,36,27},new int[]{-1,28});
    states[28] = new State(new int[]{37,29});
    states[29] = new State(-14);
    states[30] = new State(-21);
    states[31] = new State(new int[]{46,33,36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,32,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[32] = new State(-16);
    states[33] = new State(-17);
    states[34] = new State(new int[]{21,120,19,121,12,-50,7,-50,47,-50,37,-50},new int[]{-13,35});
    states[35] = new State(new int[]{36,117,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-8,36,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97});
    states[36] = new State(new int[]{25,75,26,76,30,77,29,78,27,79,28,80,47,-52,21,-52,19,-52,12,-52,7,-52,37,-52},new int[]{-16,37});
    states[37] = new State(new int[]{36,114,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-9,38,-10,82,-11,83,-12,86,-15,87,-19,97});
    states[38] = new State(new int[]{32,53,33,54,25,-56,26,-56,30,-56,29,-56,27,-56,28,-56,47,-56,21,-56,19,-56,12,-56,7,-56,37,-56},new int[]{-14,39});
    states[39] = new State(new int[]{36,111,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-10,40,-11,83,-12,86,-15,87,-19,97});
    states[40] = new State(new int[]{34,60,35,61,32,-61,33,-61,25,-61,26,-61,30,-61,29,-61,27,-61,28,-61,47,-61,21,-61,19,-61,12,-61,7,-61,37,-61},new int[]{-17,41});
    states[41] = new State(new int[]{36,108,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-11,42,-12,86,-15,87,-19,97});
    states[42] = new State(new int[]{22,84,20,85,34,-66,35,-66,32,-66,33,-66,25,-66,26,-66,30,-66,29,-66,27,-66,28,-66,47,-66,21,-66,19,-66,12,-66,7,-66,37,-66},new int[]{-18,43});
    states[43] = new State(new int[]{36,45,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-12,44,-15,87,-19,97});
    states[44] = new State(-71);
    states[45] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,46,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[46] = new State(new int[]{37,47});
    states[47] = new State(-73);
    states[48] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,49,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[49] = new State(new int[]{37,50});
    states[50] = new State(new int[]{25,75,26,76,30,77,29,78,27,79,28,80,32,53,33,54,34,60,35,61,22,84,20,85,47,-54,21,-54,19,-54,12,-54,7,-54,37,-54},new int[]{-16,51,-14,58,-17,65,-18,69});
    states[51] = new State(new int[]{36,55,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-9,52,-10,82,-11,83,-12,86,-15,87,-19,97});
    states[52] = new State(new int[]{32,53,33,54,25,-57,26,-57,30,-57,29,-57,27,-57,28,-57,47,-57,21,-57,19,-57,12,-57,7,-57,37,-57},new int[]{-14,39});
    states[53] = new State(-84);
    states[54] = new State(-85);
    states[55] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,56,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[56] = new State(new int[]{37,57});
    states[57] = new State(new int[]{32,53,33,54,34,60,35,61,22,84,20,85,25,-58,26,-58,30,-58,29,-58,27,-58,28,-58,47,-58,21,-58,19,-58,12,-58,7,-58,37,-58},new int[]{-14,58,-17,65,-18,69});
    states[58] = new State(new int[]{36,62,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-10,59,-11,83,-12,86,-15,87,-19,97});
    states[59] = new State(new int[]{34,60,35,61,32,-62,33,-62,25,-62,26,-62,30,-62,29,-62,27,-62,28,-62,47,-62,21,-62,19,-62,12,-62,7,-62,37,-62},new int[]{-17,41});
    states[60] = new State(-86);
    states[61] = new State(-87);
    states[62] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,63,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[63] = new State(new int[]{37,64});
    states[64] = new State(new int[]{34,60,35,61,22,84,20,85,32,-64,33,-64,25,-64,26,-64,30,-64,29,-64,27,-64,28,-64,47,-64,21,-64,19,-64,12,-64,7,-64,37,-64},new int[]{-17,65,-18,69});
    states[65] = new State(new int[]{36,66,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-11,107,-12,86,-15,87,-19,97});
    states[66] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,67,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[67] = new State(new int[]{37,68});
    states[68] = new State(new int[]{22,84,20,85,34,-67,35,-67,32,-67,33,-67,25,-67,26,-67,30,-67,29,-67,27,-67,28,-67,47,-67,21,-67,19,-67,12,-67,7,-67,37,-67},new int[]{-18,69});
    states[69] = new State(new int[]{36,71,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-12,70,-15,87,-19,97});
    states[70] = new State(-72);
    states[71] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,72,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[72] = new State(new int[]{37,73});
    states[73] = new State(-74);
    states[74] = new State(new int[]{25,75,26,76,30,77,29,78,27,79,28,80,47,-55,21,-55,19,-55,12,-55,7,-55,37,-55},new int[]{-16,37});
    states[75] = new State(-97);
    states[76] = new State(-98);
    states[77] = new State(-99);
    states[78] = new State(-100);
    states[79] = new State(-101);
    states[80] = new State(-102);
    states[81] = new State(new int[]{32,53,33,54,25,-60,26,-60,30,-60,29,-60,27,-60,28,-60,47,-60,21,-60,19,-60,12,-60,7,-60,37,-60},new int[]{-14,39});
    states[82] = new State(new int[]{34,60,35,61,32,-65,33,-65,25,-65,26,-65,30,-65,29,-65,27,-65,28,-65,47,-65,21,-65,19,-65,12,-65,7,-65,37,-65},new int[]{-17,41});
    states[83] = new State(new int[]{22,84,20,85,34,-70,35,-70,32,-70,33,-70,25,-70,26,-70,30,-70,29,-70,27,-70,28,-70,47,-70,21,-70,19,-70,12,-70,7,-70,37,-70},new int[]{-18,43});
    states[84] = new State(-88);
    states[85] = new State(-89);
    states[86] = new State(-75);
    states[87] = new State(new int[]{36,89,33,92,24,93,23,94,6,95,5,96,43,106,45,101,44,102,16,103,17,104},new int[]{-12,88,-15,87,-19,97});
    states[88] = new State(-76);
    states[89] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,90,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[90] = new State(new int[]{37,91});
    states[91] = new State(-77);
    states[92] = new State(-90);
    states[93] = new State(-91);
    states[94] = new State(-92);
    states[95] = new State(-93);
    states[96] = new State(-94);
    states[97] = new State(-78);
    states[98] = new State(new int[]{31,99,22,-79,20,-79,34,-79,35,-79,32,-79,33,-79,25,-79,26,-79,30,-79,29,-79,27,-79,28,-79,21,-79,19,-79,12,-79,7,-79,47,-79,37,-79});
    states[99] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,100,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[100] = new State(-49);
    states[101] = new State(-80);
    states[102] = new State(-81);
    states[103] = new State(-82);
    states[104] = new State(-83);
    states[105] = new State(-51);
    states[106] = new State(-79);
    states[107] = new State(new int[]{22,84,20,85,34,-68,35,-68,32,-68,33,-68,25,-68,26,-68,30,-68,29,-68,27,-68,28,-68,47,-68,21,-68,19,-68,12,-68,7,-68,37,-68},new int[]{-18,43});
    states[108] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,109,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[109] = new State(new int[]{37,110});
    states[110] = new State(new int[]{22,84,20,85,34,-69,35,-69,32,-69,33,-69,25,-69,26,-69,30,-69,29,-69,27,-69,28,-69,47,-69,21,-69,19,-69,12,-69,7,-69,37,-69},new int[]{-18,69});
    states[111] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,112,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[112] = new State(new int[]{37,113});
    states[113] = new State(new int[]{34,60,35,61,22,84,20,85,32,-63,33,-63,25,-63,26,-63,30,-63,29,-63,27,-63,28,-63,47,-63,21,-63,19,-63,12,-63,7,-63,37,-63},new int[]{-17,65,-18,69});
    states[114] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,115,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[115] = new State(new int[]{37,116});
    states[116] = new State(new int[]{32,53,33,54,34,60,35,61,22,84,20,85,25,-59,26,-59,30,-59,29,-59,27,-59,28,-59,47,-59,21,-59,19,-59,12,-59,7,-59,37,-59},new int[]{-14,58,-17,65,-18,69});
    states[117] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,118,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[118] = new State(new int[]{37,119});
    states[119] = new State(new int[]{25,75,26,76,30,77,29,78,27,79,28,80,32,53,33,54,34,60,35,61,22,84,20,85,47,-53,21,-53,19,-53,12,-53,7,-53,37,-53},new int[]{-16,51,-14,58,-17,65,-18,69});
    states[120] = new State(-95);
    states[121] = new State(-96);
    states[122] = new State(new int[]{47,13},new int[]{-24,123});
    states[123] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,124,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[124] = new State(-25);
    states[125] = new State(new int[]{31,126,22,-79,20,-79,34,-79,35,-79,32,-79,33,-79,25,-79,26,-79,30,-79,29,-79,27,-79,28,-79,47,-79,21,-79,19,-79});
    states[126] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,127,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[127] = new State(-48);
    states[128] = new State(new int[]{47,13,21,120,19,121},new int[]{-24,129,-13,35});
    states[129] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,130,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[130] = new State(-26);
    states[131] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,132,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[132] = new State(-27);
    states[133] = new State(new int[]{36,134});
    states[134] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,135,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[135] = new State(new int[]{37,136});
    states[136] = new State(new int[]{38,137,12,24,7,31,36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104,11,133,9,142,18,181},new int[]{-22,174,-28,175,-20,23,-29,30,-7,177,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105,-21,179,-23,180});
    states[137] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,138,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[138] = new State(new int[]{39,139});
    states[139] = new State(-37);
    states[140] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,141,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[141] = new State(-28);
    states[142] = new State(new int[]{36,143});
    states[143] = new State(new int[]{36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104},new int[]{-7,144,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105});
    states[144] = new State(new int[]{37,145});
    states[145] = new State(new int[]{38,149,12,24,7,31,36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104,11,133,9,142,18,172},new int[]{-27,146,-28,166,-20,23,-29,30,-7,168,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105,-21,170,-23,171});
    states[146] = new State(new int[]{10,147,12,-4,7,-4,43,-4,36,-4,33,-4,24,-4,23,-4,6,-4,5,-4,45,-4,44,-4,16,-4,17,-4,11,-4,9,-4,2,-4,18,-4,38,-4,39,-4});
    states[147] = new State(new int[]{38,149,12,24,7,31,36,48,33,92,24,93,23,94,6,95,5,96,43,98,45,101,44,102,16,103,17,104,11,133,9,142,18,172},new int[]{-27,148,-28,166,-20,23,-29,30,-7,168,-31,34,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-34,105,-21,170,-23,171});
    states[148] = new State(-5);
    states[149] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,150,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[150] = new State(new int[]{39,151});
    states[151] = new State(-7);
    states[152] = new State(new int[]{41,165,47,13,12,-31,7,-31,43,-31,36,-31,33,-31,24,-31,23,-31,6,-31,5,-31,45,-31,44,-31,16,-31,17,-31,11,-31,9,-31,2,-31,18,-31,38,-31,39,-31},new int[]{-24,153,-33,163});
    states[153] = new State(-29,new int[]{-32,154});
    states[154] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,155,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[155] = new State(-30);
    states[156] = new State(new int[]{47,13},new int[]{-24,157});
    states[157] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,158,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[158] = new State(-34);
    states[159] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,160,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[160] = new State(new int[]{39,161});
    states[161] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,162,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[162] = new State(-36);
    states[163] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,164,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[164] = new State(-32);
    states[165] = new State(-33);
    states[166] = new State(new int[]{47,13},new int[]{-24,167});
    states[167] = new State(-8);
    states[168] = new State(new int[]{47,13},new int[]{-24,169});
    states[169] = new State(-9);
    states[170] = new State(-10);
    states[171] = new State(-11);
    states[172] = new State(new int[]{47,13},new int[]{-24,173});
    states[173] = new State(-12);
    states[174] = new State(-38);
    states[175] = new State(new int[]{47,13},new int[]{-24,176});
    states[176] = new State(-39);
    states[177] = new State(new int[]{47,13},new int[]{-24,178});
    states[178] = new State(-40);
    states[179] = new State(-41);
    states[180] = new State(-42);
    states[181] = new State(new int[]{47,13},new int[]{-24,182});
    states[182] = new State(-43);
    states[183] = new State(new int[]{12,24,7,31,43,125,36,48,33,92,24,93,23,94,6,95,5,96,45,101,44,102,16,103,17,104,11,133,9,142,2,152,18,156,38,159,39,-35},new int[]{-3,184,-28,18,-20,23,-29,30,-6,122,-31,128,-8,74,-9,81,-10,82,-11,83,-12,86,-15,87,-19,97,-21,131,-23,140});
    states[184] = new State(-24);
    states[185] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-26, new int[]{-25,3});
    rules[2] = new Rule(-25, new int[]{8,38,-2,39,41});
    rules[3] = new Rule(-25, new int[]{8,41});
    rules[4] = new Rule(-23, new int[]{9,36,-7,37,-27});
    rules[5] = new Rule(-23, new int[]{9,36,-7,37,-27,10,-27});
    rules[6] = new Rule(-24, new int[]{47});
    rules[7] = new Rule(-27, new int[]{38,-3,39});
    rules[8] = new Rule(-27, new int[]{-28,-24});
    rules[9] = new Rule(-27, new int[]{-7,-24});
    rules[10] = new Rule(-27, new int[]{-21});
    rules[11] = new Rule(-27, new int[]{-23});
    rules[12] = new Rule(-27, new int[]{18,-24});
    rules[13] = new Rule(-1, new int[]{43});
    rules[14] = new Rule(-1, new int[]{36,-1,37});
    rules[15] = new Rule(-20, new int[]{12,-1});
    rules[16] = new Rule(-29, new int[]{7,-7});
    rules[17] = new Rule(-29, new int[]{7,46});
    rules[18] = new Rule(-2, new int[]{-4,-2});
    rules[19] = new Rule(-2, new int[]{-3});
    rules[20] = new Rule(-28, new int[]{-20});
    rules[21] = new Rule(-28, new int[]{-29});
    rules[22] = new Rule(-30, new int[]{});
    rules[23] = new Rule(-3, new int[]{-28,-28,-30,-24,-3});
    rules[24] = new Rule(-3, new int[]{-28,-24,-3});
    rules[25] = new Rule(-3, new int[]{-6,-24,-3});
    rules[26] = new Rule(-3, new int[]{-31,-24,-3});
    rules[27] = new Rule(-3, new int[]{-21,-3});
    rules[28] = new Rule(-3, new int[]{-23,-3});
    rules[29] = new Rule(-32, new int[]{});
    rules[30] = new Rule(-3, new int[]{2,-24,-32,-3});
    rules[31] = new Rule(-33, new int[]{});
    rules[32] = new Rule(-3, new int[]{2,-33,-3});
    rules[33] = new Rule(-3, new int[]{2,41});
    rules[34] = new Rule(-3, new int[]{18,-24,-3});
    rules[35] = new Rule(-3, new int[]{});
    rules[36] = new Rule(-3, new int[]{38,-3,39,-3});
    rules[37] = new Rule(-21, new int[]{11,36,-7,37,38,-3,39});
    rules[38] = new Rule(-21, new int[]{11,36,-7,37,-22});
    rules[39] = new Rule(-22, new int[]{-28,-24});
    rules[40] = new Rule(-22, new int[]{-7,-24});
    rules[41] = new Rule(-22, new int[]{-21});
    rules[42] = new Rule(-22, new int[]{-23});
    rules[43] = new Rule(-22, new int[]{18,-24});
    rules[44] = new Rule(-4, new int[]{-5,43,-24});
    rules[45] = new Rule(-5, new int[]{13});
    rules[46] = new Rule(-5, new int[]{14});
    rules[47] = new Rule(-5, new int[]{15});
    rules[48] = new Rule(-6, new int[]{43,31,-7});
    rules[49] = new Rule(-34, new int[]{43,31,-7});
    rules[50] = new Rule(-7, new int[]{-31});
    rules[51] = new Rule(-7, new int[]{-34});
    rules[52] = new Rule(-31, new int[]{-31,-13,-8});
    rules[53] = new Rule(-31, new int[]{-31,-13,36,-7,37});
    rules[54] = new Rule(-31, new int[]{36,-7,37});
    rules[55] = new Rule(-31, new int[]{-8});
    rules[56] = new Rule(-8, new int[]{-8,-16,-9});
    rules[57] = new Rule(-8, new int[]{36,-7,37,-16,-9});
    rules[58] = new Rule(-8, new int[]{36,-7,37,-16,36,-7,37});
    rules[59] = new Rule(-8, new int[]{-8,-16,36,-7,37});
    rules[60] = new Rule(-8, new int[]{-9});
    rules[61] = new Rule(-9, new int[]{-9,-14,-10});
    rules[62] = new Rule(-9, new int[]{36,-7,37,-14,-10});
    rules[63] = new Rule(-9, new int[]{-9,-14,36,-7,37});
    rules[64] = new Rule(-9, new int[]{36,-7,37,-14,36,-7,37});
    rules[65] = new Rule(-9, new int[]{-10});
    rules[66] = new Rule(-10, new int[]{-10,-17,-11});
    rules[67] = new Rule(-10, new int[]{36,-7,37,-17,36,-7,37});
    rules[68] = new Rule(-10, new int[]{36,-7,37,-17,-11});
    rules[69] = new Rule(-10, new int[]{-10,-17,36,-7,37});
    rules[70] = new Rule(-10, new int[]{-11});
    rules[71] = new Rule(-11, new int[]{-11,-18,-12});
    rules[72] = new Rule(-11, new int[]{36,-7,37,-18,-12});
    rules[73] = new Rule(-11, new int[]{-11,-18,36,-7,37});
    rules[74] = new Rule(-11, new int[]{36,-7,37,-18,36,-7,37});
    rules[75] = new Rule(-11, new int[]{-12});
    rules[76] = new Rule(-12, new int[]{-15,-12});
    rules[77] = new Rule(-12, new int[]{-15,36,-7,37});
    rules[78] = new Rule(-12, new int[]{-19});
    rules[79] = new Rule(-19, new int[]{43});
    rules[80] = new Rule(-19, new int[]{45});
    rules[81] = new Rule(-19, new int[]{44});
    rules[82] = new Rule(-19, new int[]{16});
    rules[83] = new Rule(-19, new int[]{17});
    rules[84] = new Rule(-14, new int[]{32});
    rules[85] = new Rule(-14, new int[]{33});
    rules[86] = new Rule(-17, new int[]{34});
    rules[87] = new Rule(-17, new int[]{35});
    rules[88] = new Rule(-18, new int[]{22});
    rules[89] = new Rule(-18, new int[]{20});
    rules[90] = new Rule(-15, new int[]{33});
    rules[91] = new Rule(-15, new int[]{24});
    rules[92] = new Rule(-15, new int[]{23});
    rules[93] = new Rule(-15, new int[]{6});
    rules[94] = new Rule(-15, new int[]{5});
    rules[95] = new Rule(-13, new int[]{21});
    rules[96] = new Rule(-13, new int[]{19});
    rules[97] = new Rule(-16, new int[]{25});
    rules[98] = new Rule(-16, new int[]{26});
    rules[99] = new Rule(-16, new int[]{30});
    rules[100] = new Rule(-16, new int[]{29});
    rules[101] = new Rule(-16, new int[]{27});
    rules[102] = new Rule(-16, new int[]{28});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> Program, OpenBracket, maincandeclare, CloseBracket, Eof
#line 17 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                                            {if(Compiler.stackTree.Count>0) Compiler.tree = Compiler.stackTree.Pop();}
#line default
        break;
      case 3: // start -> Program, Eof
#line 18 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                {Console.WriteLine("Unexpected end of file");  ++Compiler.errors; YYAbort();}
#line default
        break;
      case 4: // if -> If, OpenPar, exp, ClosePar, ifbody
#line 20 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                    { var nodeI = new IfNode();
					nodeI.type=Type.If;
					nodeI.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeI.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeI.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeI);}
#line default
        break;
      case 5: // if -> If, OpenPar, exp, ClosePar, ifbody, Else, ifbody
#line 26 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                               { var nodeI =new IfElseNode();
					nodeI.type=Type.If;
					nodeI.line=Compiler.line; 
					if(Compiler.stackTree.Count>0) nodeI.elseNode = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) nodeI.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeI.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeI);}
#line default
        break;
      case 6: // semicol -> SemiCol
#line 34 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                  {Compiler.line=ValueStack[ValueStack.Depth-1].i_val;
			CurrentSemanticValue.i_val=ValueStack[ValueStack.Depth-1].i_val;}
#line default
        break;
      case 12: // ifbody -> Return, semicol
#line 42 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                  { var nodeM = new ReturnNode();
		nodeM.type=Type.Main;
		nodeM.line=Compiler.line; 
		Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 13: // identPar -> Ident
#line 47 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                {CurrentSemanticValue.type=ValueStack[ValueStack.Depth-1].val;}
#line default
        break;
      case 14: // identPar -> OpenPar, identPar, ClosePar
#line 48 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                             {CurrentSemanticValue.type =ValueStack[ValueStack.Depth-2].type;}
#line default
        break;
      case 15: // read -> Read, identPar
#line 49 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                    { 
					var nodeR = new ReadNode();
					nodeR.type=Type.Read;
					nodeR.value=ValueStack[ValueStack.Depth-1].type;
				    Compiler.stackTree.Push(nodeR);}
#line default
        break;
      case 16: // write -> Write, exp
#line 54 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                { var nodeW = new WriteNode();
					nodeW.type=Type.Write;
					nodeW.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeW.right = Compiler.stackTree.Pop();
					    Compiler.stackTree.Push(nodeW);}
#line default
        break;
      case 17: // write -> Write, String
#line 60 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                 {
					var nodeS = new StringNode();
					nodeS.type=Type.String;
					nodeS.line=Compiler.line;
					nodeS.value = ValueStack[ValueStack.Depth-1].val;
					var nodeW = new WriteNode();
					nodeW.type=Type.Write;
					nodeW.right=nodeS;
				    Compiler.stackTree.Push(nodeW);}
#line default
        break;
      case 18: // maincandeclare -> declare, maincandeclare
#line 71 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
     {  
				    var nodeM = new MainNode();
					nodeM.type=Type.Main;
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 19: // maincandeclare -> main
#line 79 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
        {}
#line default
        break;
      case 22: // Anon@1 -> /* empty */
#line 85 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                            {Console.WriteLine("Syntax error");  ++Compiler.errors;
               yyerrok();
                }
#line default
        break;
      case 24: // main -> expression, semicol, main
#line 89 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
    {  
				    var nodeM = new MainNode();
					nodeM.type=Type.Main;
					nodeM.line=ValueStack[ValueStack.Depth-2].i_val;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 25: // main -> assign, semicol, main
#line 97 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                       {  
				    var nodeM = new MainNode();
					nodeM.type=Type.Main;
					nodeM.line=ValueStack[ValueStack.Depth-2].i_val;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 26: // main -> exp1, semicol, main
#line 106 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                     {  
				    var node = new StandaloneExpNode();
					node.type=Type.StandaloneExp;
					node.line=ValueStack[ValueStack.Depth-2].i_val;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(node);
				}
#line default
        break;
      case 27: // main -> while, main
#line 114 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
              {  
				    var nodeM = new MainNode();
					nodeM.type=Type.Main;
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 28: // main -> if, main
#line 122 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
            {  
				    var nodeM = new MainNode();
					nodeM.type=Type.Main;
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);
				}
#line default
        break;
      case 29: // Anon@2 -> /* empty */
#line 130 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                  {Console.WriteLine("Error while parsing (syntax or lexical error): in line {0} ", ValueStack[ValueStack.Depth-2].i_val);   ++Compiler.errors;
      yyerrok();
	              }
#line default
        break;
      case 31: // Anon@3 -> /* empty */
#line 133 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
         {Console.WriteLine("Error while parsing (syntax or lexical error)");   ++Compiler.errors;
        yyerrok();
              }
#line default
        break;
      case 33: // main -> error, Eof
#line 136 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {Console.WriteLine("Unexpected end of file");  ++Compiler.errors; YYAbort();}
#line default
        break;
      case 34: // main -> Return, semicol, main
#line 137 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                       { var nodeR = new ReturnNode();
					nodeR.type=Type.Read;
					nodeR.line=ValueStack[ValueStack.Depth-2].i_val;
					Compiler.stackTree.Push(nodeR);
					var nodeM = new MainNode();
					nodeM.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeM.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) nodeM.left = Compiler.stackTree.Pop();
				    Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 35: // main -> /* empty */
#line 146 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
    { var nodeM = new MainNode();
		 nodeM.type=Type.Main;
		 nodeM.line=Compiler.line;
		 Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 37: // while -> While, OpenPar, exp, ClosePar, OpenBracket, main, CloseBracket
#line 153 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                                                {var nodeW = new WhileNode();
					nodeW.type=Type.While;
					nodeW.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeW.right = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) nodeW.left = Compiler.stackTree.Pop();
					Compiler.stackTree.Push(nodeW);
					}
#line default
        break;
      case 38: // while -> While, OpenPar, exp, ClosePar, whilebody
#line 160 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                         {var nodeW = new WhileNode();
					nodeW.type=Type.While;
					nodeW.line=Compiler.line;
					if(Compiler.stackTree.Count>0) nodeW.right = Compiler.stackTree.Pop();
					if(Compiler.stackTree.Count>0) nodeW.left = Compiler.stackTree.Pop();
					Compiler.stackTree.Push(nodeW);
					}
#line default
        break;
      case 43: // whilebody -> Return, semicol
#line 172 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                  { var nodeM = new ReturnNode();
		 nodeM.type=Type.Return;
		 Compiler.stackTree.Push(nodeM);}
#line default
        break;
      case 44: // declare -> vtype, Ident, semicol
#line 176 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                              {var node = new DeclarationNode(); 
						  node.type=Type.Declaration;
						  node.line=Compiler.line;
						  node.varType=Compiler.GetValType(ValueStack[ValueStack.Depth-3].type); node.ident=ValueStack[ValueStack.Depth-2].val;
						  if(Compiler.variables.ContainsKey(ValueStack[ValueStack.Depth-2].val)) 
						  {	
							string s=ValueStack[ValueStack.Depth-2].val;
							Console.WriteLine("Semantic error. Variable {0} already declared. Error in line {1}",s,Compiler.line);
							++Compiler.errors;
						  }
						  else
							 Compiler.variables.Add(ValueStack[ValueStack.Depth-2].val,Compiler.GetValType(ValueStack[ValueStack.Depth-3].type));
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 45: // vtype -> Int
#line 190 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
           {CurrentSemanticValue.type="int";}
#line default
        break;
      case 46: // vtype -> Double
#line 191 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
          {CurrentSemanticValue.type="double";}
#line default
        break;
      case 47: // vtype -> Bool
#line 192 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
        {CurrentSemanticValue.type = "bool";}
#line default
        break;
      case 48: // assign -> Ident, Assign, exp
#line 194 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                          {var node = new AssignNode(); 
						   node.type = Type.Assign;
						   node.line=Compiler.line;
						   node.ident=ValueStack[ValueStack.Depth-3].val;
						   	if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 49: // assignMid -> Ident, Assign, exp
#line 201 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                             {var node = new AssignMidNode(); 
						   node.type = Type.Assign;
						   node.line=Compiler.line;
						   node.ident=ValueStack[ValueStack.Depth-3].val;
						   	if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 52: // exp1 -> exp1, logicop, exp2
#line 211 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                         {var node = new LogicNode(); 			
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetLogicType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 53: // exp1 -> exp1, logicop, OpenPar, exp, ClosePar
#line 217 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                      {var node = new LogicNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetLogicType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 56: // exp2 -> exp2, relatiop, exp3
#line 227 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
  {
		 var node = new RelationNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetRelationType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 57: // exp2 -> OpenPar, exp, ClosePar, relatiop, exp3
#line 235 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
   {var node = new RelationNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetRelationType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 58: // exp2 -> OpenPar, exp, ClosePar, relatiop, OpenPar, exp, ClosePar
#line 242 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
   {var node = new RelationNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetRelationType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 59: // exp2 -> exp2, relatiop, OpenPar, exp, ClosePar
#line 249 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
   {var node = new RelationNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetRelationType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 61: // exp3 -> exp3, addop, exp4
#line 257 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                      {var node = new AddNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetAddType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 62: // exp3 -> OpenPar, exp, ClosePar, addop, exp4
#line 263 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                   {var node = new AddNode(); 
					node.line=Compiler.line;
					 if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetAddType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 63: // exp3 -> exp3, addop, OpenPar, exp, ClosePar
#line 269 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                   {var node = new AddNode(); 
					node.line=Compiler.line;
					 if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetAddType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 64: // exp3 -> OpenPar, exp, ClosePar, addop, OpenPar, exp, ClosePar
#line 276 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
     {var node = new AddNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetAddType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 66: // exp4 -> exp4, mulop, exp5
#line 284 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                       {var node = new MulNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetMulType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 67: // exp4 -> OpenPar, exp, ClosePar, mulop, OpenPar, exp, ClosePar
#line 290 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                                    {var node = new MulNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetMulType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 68: // exp4 -> OpenPar, exp, ClosePar, mulop, exp5
#line 296 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                    {var node = new MulNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetMulType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 69: // exp4 -> exp4, mulop, OpenPar, exp, ClosePar
#line 302 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                    {var node = new MulNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetMulType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 71: // exp5 -> exp5, bitop, exp6
#line 310 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                       {var node = new BitNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetBitType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 72: // exp5 -> OpenPar, exp, ClosePar, bitop, exp6
#line 316 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                     {var node = new BitNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetBitType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 73: // exp5 -> exp5, bitop, OpenPar, exp, ClosePar
#line 322 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                      {var node = new BitNode(); 
					node.line=Compiler.line;
					 if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetBitType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 74: // exp5 -> OpenPar, exp, ClosePar, bitop, OpenPar, exp, ClosePar
#line 328 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                                                      {var node = new BitNode(); 
					node.line=Compiler.line;
					if(Compiler.stackTree.Count>0) node.right = Compiler.stackTree.Pop();
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetBitType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 76: // exp6 -> unary, exp6
#line 336 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                   {var node = new UnaryNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetUnaryType(ValueStack[ValueStack.Depth-2].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 77: // exp6 -> unary, OpenPar, exp, ClosePar
#line 341 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                              {var node = new UnaryNode(); 
					node.line=Compiler.line;
				    if(Compiler.stackTree.Count>0) node.left = Compiler.stackTree.Pop();
					node.type = Compiler.GetUnaryType(ValueStack[ValueStack.Depth-4].type);
					Compiler.stackTree.Push(node);}
#line default
        break;
      case 79: // term -> Ident
#line 348 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
            {var node = new IdentNode();
			node.line=Compiler.line;
			node.type=Type.Ident;
			node.ident = ValueStack[ValueStack.Depth-1].val;
			Compiler.stackTree.Push(node);}
#line default
        break;
      case 80: // term -> RealNumber
#line 353 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
              {var node = new DoubleNode();	
					node.type=Type.Double;
					node.line=Compiler.line;
					node.value=Double.Parse(ValueStack[ValueStack.Depth-1].val,System.Globalization.CultureInfo.InvariantCulture);
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 81: // term -> IntNumber
#line 358 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {var node = new IntNode();
					node.type=Type.Int;
					node.line=Compiler.line;
					node.value=Int32.Parse(ValueStack[ValueStack.Depth-1].val);
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 82: // term -> True
#line 363 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
        {var node = new BoolNode();
					node.type=Type.Bool;
					node.line=Compiler.line;
					node.value=true;
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 83: // term -> False
#line 368 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
         {var node = new BoolNode();
					node.type=Type.Bool;
					node.line=Compiler.line;
					node.value=false;
						  Compiler.stackTree.Push(node);}
#line default
        break;
      case 84: // addop -> Plus
#line 374 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {CurrentSemanticValue.type="+";}
#line default
        break;
      case 85: // addop -> Minus
#line 375 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
          {CurrentSemanticValue.type="-";}
#line default
        break;
      case 86: // mulop -> Multiply
#line 377 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                 {CurrentSemanticValue.type="*";}
#line default
        break;
      case 87: // mulop -> Divide
#line 378 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
          {CurrentSemanticValue.type="/";}
#line default
        break;
      case 88: // bitop -> BitOr
#line 379 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {CurrentSemanticValue.type="|";}
#line default
        break;
      case 89: // bitop -> BitAnd
#line 380 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
            {CurrentSemanticValue.type="&";}
#line default
        break;
      case 90: // unary -> Minus
#line 382 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
              {CurrentSemanticValue.type="-";}
#line default
        break;
      case 91: // unary -> BitNegation
#line 383 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                {CurrentSemanticValue.type="~";}
#line default
        break;
      case 92: // unary -> Negation
#line 384 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {CurrentSemanticValue.type="!";}
#line default
        break;
      case 93: // unary -> IntConv
#line 385 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
            {CurrentSemanticValue.type="(int)";}
#line default
        break;
      case 94: // unary -> DoubleConv
#line 386 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
               {CurrentSemanticValue.type="(double)";}
#line default
        break;
      case 95: // logicop -> Or
#line 388 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {CurrentSemanticValue.type="||";}
#line default
        break;
      case 96: // logicop -> And
#line 389 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
        {CurrentSemanticValue.type="&&";}
#line default
        break;
      case 97: // relatiop -> Equal
#line 391 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                 {CurrentSemanticValue.type="==";}
#line default
        break;
      case 98: // relatiop -> NotEqual
#line 392 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
             {CurrentSemanticValue.type="!=";}
#line default
        break;
      case 99: // relatiop -> Greater
#line 393 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
           {CurrentSemanticValue.type=">";}
#line default
        break;
      case 100: // relatiop -> Smaller
#line 394 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
            {CurrentSemanticValue.type="<";}
#line default
        break;
      case 101: // relatiop -> GreaterOrEqual
#line 395 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                  {CurrentSemanticValue.type=">=";}
#line default
        break;
      case 102: // relatiop -> SmallerOrEqual
#line 396 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"
                   {CurrentSemanticValue.type="<=";}
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 400 "C:\Users\przem\source\repos\Compilator\Compilator\kompilator.y"

public Parser(Scanner scanner) : base(scanner) { }
#line default
}
}
